apiVersion: v1
kind: Service
metadata:
  name: url-service-db-service
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    role: mongo
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: url-service-statefulset
spec:
  serviceName: url-service-db-service
  replicas: 1
  template:
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongod-container
          image: mongo
          env:
            - name: MACHINE_MEMORY
              value: "500Mi"
            - name: MONGO_USER
              value: "admin"
            - name: MONGO_PASSWORD
              value: "admin123"
          ports:
            - containerPort: 27017
