apiVersion: v1
kind: Service
metadata:
  name: key-generation-service-db
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    role: mongo
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: key-generation-service
spec:
  serviceName: key-generation-service-db
  replicas: 1
  selector:
    matchLabels:
      role: mongo
  template:
    metadata:
      labels:
        role: mongo
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongod-container
          image: mongo
          env:
            - name: MACHINE_MEMORY
              value: "500Mi"
            - name: MONGO_USER
              value: "admin"
            - name: MONGO_PASSWORD
              value: "admin123"
          ports:
            - containerPort: 27017
