apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: kafka-pdb
  namespace: app
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: kafka
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: app
spec:
  serviceName: kafka
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  updateStrategy:
    type: OnDelete
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: kafka
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "app"
                      operator: In
                      values:
                        - kafka
                topologyKey: "kubernetes.io/hostname"

      nodeSelector:
        pool: app
      containers:
        - name: kafka
          env:
            - name: KAFKA_JMX_OPTS
              value: "-Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=1099 -Dcom.sun.management.jmxremote.rmi.port=1099"
            - name: KAFKA_HEAP_OPTS
              value: "-Xms1G -Xmx1G"
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: "kafka"
            - name: KAFKA_ARGS
              value: "--override zookeeper.connect=zookeeper-0.zookeeper:2181,zookeeper-1.zookeeper:2181,zookeeper-2.zookeeper:2181 --override log.retention.bytes=1000000000 --override log.retention.hours=168 --override num.partitions=16 --override offsets.topic.replication.factor=3 --override default.replication.factor=3 --override min.insync.replicas=2"
              # https://docs.confluent.io/current/installation/configuration/broker-configs.html
          image: neowu/kafka:2.6.0
          readinessProbe:
            tcpSocket:
              port: 9092
            timeoutSeconds: 5
            periodSeconds: 10
            initialDelaySeconds: 40
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            limits:
              memory: 2Gi
      priorityClassName: critical
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: ssd
        resources:
          requests:
            storage: 128Gi
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: app
spec:
  clusterIP: None
  ports:
    - port: 9092
  selector:
    app: kafka
