apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: kafka-pdb
  namespace: app
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: kafka
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: app
spec:
  serviceName: kafka
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  updateStrategy:
    type: OnDelete
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          env:
            - name: KAFKA_JMX_OPTS
              value: "-Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=1099 -Dcom.sun.management.jmxremote.rmi.port=1099"
            - name: KAFKA_HEAP_OPTS
              value: "-Xms1G -Xmx1G"
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: "kafka"
          image: neowu/kafka:2.6.0
          readinessProbe:
            tcpSocket:
              port: 9092
            timeoutSeconds: 5
            periodSeconds: 10
            initialDelaySeconds: 40
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: app
spec:
  clusterIP: None
  ports:
    - port: 9092
  selector:
    app: kafka
