apiVersion: v1
kind: Service
metadata:
  name: mongo-db
  namespace: app
spec:
  selector:
    app: mongo-db
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-db
  namespace: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mongo-db
  serviceName: "mongo-db"
  template:
    metadata:
      labels:
        app: mongo-db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo
          command:
            - mongod
            - "--replSet"
            - rs0
            - "--smallfiles"
            - "--noprealloc"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: mongo-persistent-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 100Gi
