apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-service
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: url-service
    spec:
      containers:
        - name: website
          image: ghcr.io/harrison-yck/short-url/url-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: https
              containerPort: 8443
          livenessProbe:
            httpGet:
              path: /health-check
              scheme: HTTPS
              port: 8443
            initialDelaySeconds: 15
            timeoutSeconds: 15
          readinessProbe:
            httpGet:
              path: /health-check
              scheme: HTTPS
              port: 8443
            initialDelaySeconds: 5
            timeoutSeconds: 3
          resources:
            requests:
              cpu: 200m
              memory: 384Mi
            limits:
              cpu: 1000m
              memory: 384Mi
---
apiVersion: v1
kind: Service
metadata:
  name: url-service
spec:
  ports:
    - name: https
      port: 443
      targetPort: 8443
  selector:
    app: url-service
