apiVersion: v1
kind: Service
metadata:
  name: url-service-service-db
  namespace: app
spec:
  selector:
    app: url-service-service-db
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-service-service-db
  namespace: app
  labels:
    app: url-service-service-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-service-service-db
  template:
    metadata:
      labels:
        app: url-service-service-db
    spec:
      containers:
        - name: url-service-service-db
          image: mongo
          ports:
            - containerPort: 27017
