apiVersion: v1
kind: Service
metadata:
  name: key-generation-service-db
spec:
  ports:
    - port: 27017
      protocol: TCP
  selector:
    role: mongo
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: key-generation-service-db
  labels:
    app: key-generation-service-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: key-generation-service-db
  template:
    metadata:
      labels:
        app: key-generation-service-db
    spec:
      containers:
        - name: key-generation-service-db
          image: mongo
          ports:
            - containerPort: 27017
