apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: website
    spec:
      nodeSelector:
        pool: app
      containers:
        - name: website
          image: ghcr.io/harrison-yck/short-url/website:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: https
              containerPort: 8443
          livenessProbe:
            httpGet:
              path: /health-check
              scheme: HTTPS
              port: 8443
            initialDelaySeconds: 15
            timeoutSeconds: 15
          readinessProbe:
            httpGet:
              path: /health-check
              scheme: HTTPS
              port: 8443
            initialDelaySeconds: 5
            timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: website
  namespace: app
spec:
  type: NodePort
  ports:
    - name: https
      port: 443
      targetPort: 8443
  selector:
    app: website

