apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-kibana
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-kibana
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: log-kibana
    spec:
      nodeSelector:
        pool: ops
      containers:
        - name: log-kibana
          image: docker.elastic.co/kibana/kibana-oss:7.10.0
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "http://log-es-0.log-es:9200"
            - name: TELEMETRY_ENABLED
              value: "false"
          readinessProbe:
            httpGet:
              path: /api/status
              scheme: HTTP
              port: 5601
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: log-kibana
  namespace: app
spec:
  type: NodePort
  ports:
    - port: 5601
      nodePort: 30101
  selector:
    app: log-kibana
