name: CI

on:
  push:
    branches: [ release ]

defaults:
  run:
    working-directory: core-ng-url-shortener

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Job Started to Slack
        uses: act10ns/slack@v1
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: starting
          channel: '#ci'
          if: always()

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup docker
        uses: docker/setup-buildx-action@v1

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 15

      - name: Setup gradle permission
        run: chmod +x gradlew

      - name: Gradle check and build
        run: ./gradlew check && ./gradlew -Penv="dev" docker

      - name: Tar Build
        run: tar -cvf ./build.tar ./core-ng-url-shortener

      - name: Upload Build
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ./build.tar

  build-website-image:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: download
        uses: actions/download-artifact@v2
        with:
          name: build

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGES_TOKEN }}

      - name: Untar Build
        run: tar -zxvf ${{steps.download.outputs.download-path}}

      - name: Build and Push Image
        uses: docker/build-push-action@v2
        with:
          context: ${{steps.download.outputs.download-path}}/core-ng-url-shortener/build/frontend/website/docker
          push: true
          tags: ghcr.io/harrison-yck/short-url/website:latest

  build-scdeduler-service-image:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: download
        uses: actions/download-artifact@v2
        with:
          name: build

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGES_TOKEN }}

      - name: Untar Build
        run: tar -zxvf ${{steps.download.outputs.download-path}}

      - name: Build and Push Image
        uses: docker/build-push-action@v2
        with:
          context: ${{steps.download.outputs.download-path}}/core-ng-url-shortener/build/backend/scheduler-service/docker
          push: true
          tags: ghcr.io/harrison-yck/short-url/scheduler-service:latest

  build-key-generation-service-image:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: download
        uses: actions/download-artifact@v2
        with:
          name: build

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGES_TOKEN }}

      - name: Untar Build
        run: tar -zxvf ${{steps.download.outputs.download-path}}

      - name: Build and Push Image
        uses: docker/build-push-action@v2
        with:
          context: ${{steps.download.outputs.download-path}}/core-ng-url-shortener/build/backend/key-generation-service/docker
          push: true
          tags: ghcr.io/harrison-yck/short-url/key-generation-service:latest

  build-url-service-image:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: download
        uses: actions/download-artifact@v2
        with:
          name: build

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGES_TOKEN }}

      - name: Untar Build
        run: tar -zxvf ${{steps.download.outputs.download-path}}

      - name: Build and Push Image
        uses: docker/build-push-action@v2
        with:
          context: ${{steps.download.outputs.download-path}}/core-ng-url-shortener/build/backend/url-service/docker
          push: true
          tags: ghcr.io/harrison-yck/short-url/url-service:latest

  slack-notification:
    runs-on: ubuntu-latest
    needs: [ build, build-website-image, build-scdeduler-service-image, build-key-generation-service-image, build-url-service-image ]
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#ci'
        if: always()




