name: CI

on:
  push:
    branches: [ release ]

defaults:
  run:
    working-directory: core-ng-url-shortener

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Runs the Super-Linter action
    - name: Run Super-Linter
      uses: github/super-linter@v3
      env:
        DEFAULT_BRANCH: master
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
