name: CI

on:
  push:
    branches: [ release ]

defaults:
  run:
    working-directory: core-ng-url-shortener

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup docker
        uses: docker/setup-buildx-action@v1

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 15

      - name: Setup gradle permission
        run: chmod +x gradlew

      - name: Gradle check and Build Docker
        run: ./gradlew check && ./gradlew -Penv="dev" docker

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGES_TOKEN }}

  build-website:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Build Website
        uses: docker/build-push-action@v2
        with:
          context: ./core-ng-url-shortener/build/frontend/website/docker
          file: ./core-ng-url-shortener/build/frontend/website/docker/Dockerfile
          push: true
          tags: ghcr.io/harrison-yck/shorturl/website:latest

  build-scheduler-service:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Build Scdeduler Service
        uses: docker/build-push-action@v2
        with:
          context: ./core-ng-url-shortener/build/backend/scheduler-service/docker
          file: ./core-ng-url-shortener/build/backend/scheduler-service/docker/Dockerfile
          push: true
          tags: ghcr.io/harrison-yck/shorturl/scheduler-service:latest

  build-key-generation-service:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Build Key Generation Service
        uses: docker/build-push-action@v2
        with:
          context: ./core-ng-url-shortener/build/backend/key-generation-service/docker
          file: ./core-ng-url-shortener/build/backend/key-generation-service/docker/Dockerfile
          push: true
          tags: ghcr.io/harrison-yck/shorturl/key-generation-service:latest

  build-url-service:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Build Url Service
        uses: docker/build-push-action@v2
        with:
          context: ./core-ng-url-shortener/build/backend/url-service/docker
          file: ./core-ng-url-shortener/build/backend/url-service/docker/Dockerfile
          push: true
          tags: ghcr.io/harrison-yck/shorturl/url-service:latest

