name: CI

on:
  push:
    branches: [ master ]

defaults:
  run:
    working-directory: core-ng-url-shortener

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Job Started to Slack
        uses: act10ns/slack@v1
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: starting
          channel: '#ci'
          if: always()

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup docker
        uses: docker/setup-buildx-action@v1

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 15

      - name: Setup gradle permission
        run: chmod +x gradlew

      - name: Gradle check and build
        run: ./gradlew check && ./gradlew -Penv="dev" docker

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGES_TOKEN }}

      - name: Build and Push Website Image
        uses: docker/build-push-action@v2
        with:
          context: ./core-ng-url-shortener/build/frontend/website/docker
          push: true
          tags: ghcr.io/harrison-yck/short-url/website:latest


      - name: Build and Push Scheduler Image
        uses: docker/build-push-action@v2
        with:
          context: ./core-ng-url-shortener/build/backend/scheduler-service/docker
          push: true
          tags: ghcr.io/harrison-yck/short-url/scheduler-service:latest


      - name: Build and Push Key Generator Image
        uses: docker/build-push-action@v2
        with:
          context: ./core-ng-url-shortener/build/backend/key-generation-service/docker
          push: true
          tags: ghcr.io/harrison-yck/short-url/key-generation-service:latest


      - name: Build and Push Url Service Image
        uses: docker/build-push-action@v2
        with:
          context: ./core-ng-url-shortener/build/backend/url-service/docker
          push: true
          tags: ghcr.io/harrison-yck/short-url/url-service:latest

  slack-notification:
    runs-on: ubuntu-latest
    needs: [ build ]
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#ci'
        if: always()




